name: Update Posts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy session file
        run: |
          mkdir -p /tmp/.instaloader-runner
          cp session-bat.8797744 /tmp/.instaloader-runner/session-bat.8797744

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14

      - name: Install Instaloader
        run: pip install instaloader

      - name: Fetch Instagram posts
        run: python fetch.py
